### PR TITLE
Zuul migration

### PR DESCRIPTION
**Pull request by rgarrigue**

### CODE REVIEW

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by fblackburn1** [comment]
The issue was the README
Now it's because the version is not greater than the upstream version. Since we don't modify anything on this repo. I propose to close this PR and consider the migration a success

**Comment by fblackburn1** [comment]
**DO NOT MERGE THIS PR**
A push a new commit to bump changelog to trigger a successfuly build

But it would be useless to merge it and trigger a real build, since no modification is done

**Pull request closed without merging**
